---
- name: daemon reload
  systemd:
    daemon_reload: true

- name: restart systemd-resolved
  systemd:
    name: systemd-resolved
    state: restarted
    daemon_reload: true
  when: ansible_distribution == 'Ubuntu'

- name: restart AdGuardHome
  systemd:
    name: AdGuardHome
    state: restarted
    daemon_reload: true
  when: ansible_distribution == 'Ubuntu'
