---
# based on https://github.com/WoodenDoors/ansible-adguard-home
- name: Ensure user exists
  user:
    name: "{{ adguard_home_user }}"
    state: present

- name: Ensure base directory exists
  file:
    dest: "{{ adguard_home_base_path }}"
    owner: "{{ adguard_home_user }}"
    group: "{{ adguard_home_group }}"
    recurse: yes
    state: directory

- name: Download AdGuardHome
  get_url:
    url: "{{ adguard_home_download_url }}"
    dest: "{{ adguard_home_tmp_path }}"

- name: Unarchive AdGuardHome
  unarchive:
    copy: no
    src: "{{ adguard_home_tmp_path }}/{{ adguard_home_archive }}"
    dest: "{{ adguard_home_base_path }}"
    owner: "{{ adguard_home_user }}"
    group: "{{ adguard_home_group }}"
  become: yes
  become_user: "{{ adguard_home_user }}"

- name: Restore AdGuard settings
  template:
    src: AdGuardHome.yaml.j2
    dest: "{{ adguard_home_path }}/AdGuardHome.yaml"
    owner: root
    group: root
    mode: 0644
    force: yes

- name: Install AdGuardHome
  command: "{{ adguard_home_executable }} -s install"
  become: yes
  become_user: "{{ adguard_home_user }}"
  changed_when: false

- include_tasks: networkfix.yml
  when: '"Ubuntu" in OS.stdout or "Linux" in OS.stdout'

- name: Set AdGuardHome permissions
  command: "setcap CAP_NET_BIND_SERVICE=+eip {{ adguard_home_executable }}"
  become: yes
  become_user: "{{ adguard_home_user }}"
  changed_when: false
