---
wireguard_PersistentKeepalive: 0
wireguard_config_path: "configs/{{ IP_subject_alt_name }}/wireguard/"
wireguard_pki_path: "{{ wireguard_config_path }}/.pki/"
wireguard_interface: wg0
wireguard_port_avoid: 53
wireguard_port_actual: 51820
keys_clean_all: false
wireguard_dns_servers: >-
  {{ local_service_ip }}{{ ', ' + local_service_ipv6 if ipv6_support else '' }}
wireguard_client_ip: >-
  {{ wireguard_network_ipv4 | ipaddr(index|int+2) }}
  {{ ',' + wireguard_network_ipv6 | ipaddr(index|int+2) if ipv6_support else '' }}
wireguard_server_ip: >-
  {{ wireguard_network_ipv4 | ipaddr('1') }}
  {{ ',' + wireguard_network_ipv6 | ipaddr('1') if ipv6_support else '' }}
pihole_allowed_ips: "{{ local_service_ip }}/32, {{ wireguard_network_ipv4 | ipaddr(1) }}{{ ', ' + local_service_ipv6 + '/128' if ipv6_support else '' }}{{ ', ' + wireguard_network_ipv6 | ipaddr(1) if ipv6_support else '' }}"
