---
- name: Pi-hole wildcard tools | Download wildcard generator
  get_url:
    url: https://raw.githubusercontent.com/mmotti/pihole-gravity-wildcards/master/generateGravityWildcards.sh
    dest: /usr/local/bin/generateGravityWildcards.sh
    owner: root
    group: root
    mode: 0755

- name: Pi-hole wildcard tools | Download dnsmasq wildcards
  get_url:
    url: https://raw.githubusercontent.com/mmotti/pihole-filter-lists/master/fetchFilterLists.sh
    dest: /usr/local/bin/fetchFilterLists.sh
    owner: root
    group: root
    mode: 0755

- name: Pi-hole wildcard tools | Download gravity optimizer
  get_url:
    url: https://raw.githubusercontent.com/mmotti/pihole-gravity-optimise/master/gravityOptimise.py
    dest: /usr/local/bin/gravityOptimise.py
    owner: root
    group: root
    mode: 0755

- name: Pi-hole wildcard tools | Add scripts to cron
  template:
    src: wildcards.j2
    dest: /etc/cron.d/wildcards

- name: Pi-hole wildcard tools | Run generateGravityWildcards
  command: /usr/local/bin/generateGravityWildcards.sh
  changed_when: false

- name: Pi-hole wildcard tools | Run fetchFilterLists
  command: /usr/local/bin/fetchFilterLists.sh
  changed_when: false

- name: Pi-hole wildcard tools | Run gravityOptimise
  command: "python3 /usr/local/bin/gravityOptimise.py"
  changed_when: false
